name: Cronjob-trigger Onrelease
on:
  push:
    tags:
      - 'v*'
jobs:
  test-kubeless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download
      - run: make bootstrap
      - run: make binary
      - run: make test
      - run: make validation
      - name: Store cronjob-trigger-controller binary
        uses: actions/upload-artifact@v2
        with:
          name: cronjob-trigger-controller
          path: ~/go/bin/cronjob-trigger-controller
  build-images-onrelease:
    runs-on: ubuntu-latest
    env:
      CRONJOB_CONTROLLER_IMAGE_NAME: ciscom31/cronjob-controller-image
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: go mod download
      - run: make bootstrap
      - run: |
          export CONTROLLER_TAG="${GITHUB_REF_NAME}"
          export CRONJOB_CONTROLLER_IMAGE=${CRONJOB_CONTROLLER_IMAGE_NAME}:${CONTROLLER_TAG}
          export PATH=$(pwd)/bats/libexec:~/go/bin:/home/runner/work/:$PATH
          export GOPATH=$(pwd)/go
          ./script/pull-or-build-image.sh cronjob-controller-image
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"   
          images=(
            cronjob-trigger-controller
          )
          docker tag cronjob-controller-image:${CONTROLLER_TAG} cronjob-trigger-controller:${CONTROLLER_TAG}
          docker push cronjob-trigger-controller:${CONTROLLER_TAG}
          docker tag cronjob-trigger-controller:${CONTROLLER_TAG} cronjob-trigger-controller:latest
          docker push cronjob-trigger-controller:latest
